name: Build Api Server
on:
  push:
    branches:
      - develop
    tags:
      - Api-v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image: deploy-testgit
      tag: latest
    strategy:
      #모듈들 명
      matrix:
        kotlin-version: [ 1.5.31 ]
        java-version: [ 11 ]
    outputs:
      #버전
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          kotlin-version: ${{ matrix.kotlin-version }}
          distribution: 'adopt'

      # branch tags -> version (without v)
      - name: Get the version
        id: get_version
        run: |
          RELEASE_VERSION_WITHOUT_V="$(cut -d'v' -f2 <<< ${GITHUB_REF#refs/*/})"
          echo "RELEASE_VERSION_WITHOUT_V=$RELEASE_VERSION_WITHOUT_V" >> $GITHUB_ENV

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build :Whatnow-Api:build --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      # docker build / push to NCP Container Registry
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Whatnow-Api
          # image push 최적화
          push: true
          tags: ${{secrets.NCP_CONTAINER_REGISTRY}}/whatnow-api:latest